### ISSUE TITLE
set up Rails 3 for BT in parallel with 2.3.5 development

### ISSUE THREAD

**Issue by arsturges** [arsturges/RVB#23]
I want to start the Building Technologies application in Rails 3, but still be able to develop RVB in 2.3.5. Unless migrating RVB into Rails 3 would be a good idea.

**Comment by twinge** [comment]
on anything but windows, the best way to do that is RVM (Ruby version manager). On windows, just install both version of rails, cross your fingers, and it should be fine. ;)
